### ISSUE TITLE
Launch process silently

### ISSUE THREAD

**Issue by Qwash** [diversenok/ExecutionMaster#2]
Hello, can u please make a small tool for silent start a process with the debug flag so I can bypass IFEO
(need it for automation)

**Comment by diversenok** [comment]
Sure. **[JustRun.zip](https://github.com/diversenok/ExecutionMaster/files/2101866/JustRun.zip)**

There are four slightly different versions of the same program with a combination of x64 / x86 and GUI / CUI.

#### You should take into account that:
 - x86 (aka 32-bit) version **can't** run 64-bit programs on 64-bit systems. Use x64 version in this case.
 - The difference between CUI (Console subsystem) and GUI (Graphical subsystem) programs is very thin. However, you can notice it when running programs from the command line: console applications don't usually wait for GUI applications and don't share a console with them.
 - GUI version doesn't spawn a console, but CUI does.

**Comment by Qwash** [comment]
Thank you very much! that helped me a lot!
Just a little edit and it will be perfect: It keeps running in the background until launched process closed

**Comment by diversenok** [comment]
By default, **JustRun** (along with all other actions executables) waits for the newly created process until it closes and then exits with the same exit code. It is necessary if the caller needs the exit code value or the wait itself.

I've added a new key so you can override this behavior by specifying `/nowait` as the first parameter. In this case, it exits immediately after creating a new process. Note that in all situations it tries to replace the parent process of the newly created process with the caller process.

**[JustRun-v2.zip](https://github.com/diversenok/ExecutionMaster/files/2105466/JustRun-v2.zip)**
